- 👋 Hi, I’m Laxx Bot
- 👀 I’m interested in games and girls
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns:Brasil...
- ⚡ Fun fact: ...

<!---
Lalah-web/Lalah-web is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
